### ISSUE TITLE
Spam posted

### ISSUE THREAD

**Issue by matthewpersico** [davorg/planetperl#11]
Three posts were picked up from blog.perl.org with no Perl content, including http://blogs.perl.org/users/bobpaul/2020/11/global-coronavirus-cases-upward-thrust-by-way-of-unmarried-day-file-of-half-a-million.html

I also reported to blogs.perl.org.

**Comment by davorg** [comment]
I've temporarily removed bpo from the configuration. That has the unfortunate side-effect of removing all other bpo posts, but that's the only option I have.

Usually, Aristotle is quick to respond to spam reports, so I hope to be able to reinstate them soon.

**Comment by davorg** [comment]
The problematic entries have gone from bpo, so I've reinstated the feed and rebuilt the page.

**Comment by ap** [comment]
Thanks. There has been an annoying uptick in this type of spam lately and I’m getting tired of chasing the trash… I’m noodling on some kind of whitelisting to deny spam any way onto the front page.
