### ISSUE TITLE
Is Perl Weekly supposed to be broken into multiple entries?

### ISSUE THREAD

**Issue by matthewpersico** [davorg/planetperl#12]
It's suboptimal to have to scroll through all the Perl Weekly entries posted as individual items, especially the jobs. I think one entry for The Perl Weekly would be enough.

**Comment by davorg** [comment]
Unfortunately, that's how the Perl Weekly web feed is built. I agree that one feed item would be more useful. If you can persuade Gabor to change the way the web feed works (or build another feed for me that concatenates the items from the original feed), then that would make me very happy.

(Or maybe I could have a think about a way to do this within Perlanet itself.)

**Comment by davorg** [comment]
I raised this as an issue (https://github.com/szabgab/perlweekly/issues/368) on PerlWeekly. Gabor agreed it was a good idea, so I've also sent a PR (https://github.com/szabgab/perlweekly/pull/369). Just waiting for him to merge it.

**Comment by matthewpersico** [comment]
WooHoo! That's great! Thanks. Have you been at TPC? I promoted the site in Mark Gardner's BOF on blogging.

**Comment by davorg** [comment]
See https://perlweekly.com/index.rss. And that's the feed we're now using.
