### ISSUE TITLE
Per user toggle for headlines and source footers only

### ISSUE THREAD

**Issue by matthewpersico** [davorg/planetperl#13]
How difficult would it be to code up a toggle (Summary/Detail) so that one can only see the titles and the sources for items, no text? That would allow me to skip the breakout of all the jobs and stories from Perl Weekly (which I read directly), and that would solve #6 and #12.

**Comment by davorg** [comment]
I don't think that would be too hard.

But, honestly, given the number of visitors the site gets (fewer than ten a day), I'm not sure that I can justify spending the time on it.

Patches welcome though, of course :-)

**Comment by matthewpersico** [comment]
Really? That's ALL? Well, we need to change that first. :-)

**Comment by matthewpersico** [comment]
If I knew what to patch, I'd have given you a PR. 😁 . Seriously, though would I need to patch this site or the underlying software (which might make a nice link in a README, by the way... 😉 )?

**Comment by davorg** [comment]
It'll be a change to the [index.tt](https://github.com/davorg/planetperl/blob/master/index.tt) in this repo.

There's already a `<div>` (with `class="card"`) for each story and, within that, sub-`div` with classes of `card-header`, `card-body` and `card-footer`. You could use those with jQuery's `.show()` and `.hide()` methods to show/hide all the card bodies at once. If you wanted to display an individual card's body then you'd want to add a unique id to each story.

**Comment by davorg** [comment]
I've put together a very basic show/hide setting for the bodies of the stories. Commit https://github.com/davorg/planetperl/commit/15b77e1e26d04d15d4d3c179701a5663efd0737d shows how it's done. You could use that as a basis for anything more complicated that you wanted to add.

**Comment by matthewpersico** [comment]
That's good enough. Hide text, see title, click title. Or show text if I am lazy.

**Comment by matthewpersico** [comment]
This is fantastic. Open the page. Toogle to hide. Scan the titles. Click the ones I want to see. 

Thank you
