### ISSUE TITLE
Fix opacity

### ISSUE THREAD

**Issue by thibaultduponchelle** [davorg/planetperl#14]
Hello,

First I'm happy to have discovered perl planetarium that seems to do a pretty decent job at aggregating Perl blog posts :+1:

I feel like there is a problem with opacity, the background is too visible and is embarrassing to read the text.

Could you please change it?

**Comment by davorg** [comment]
Yes, I'd been meaning to make that less annoying, but forgot about it. Thanks for the reminder.

For now, I've turned the opacity off. But I'll get back to it at a later date.

Might take ten minutes for the site to rebuild, and you'll want to do a hard refresh of the CSS file.

**Comment by thibaultduponchelle** [comment]
Thank you a lot 🙏🏼
