### ISSUE TITLE
Current display is out of order, looks like missing items

### ISSUE THREAD

**Issue by matthewpersico** [davorg/planetperl#18]
![image](https://user-images.githubusercontent.com/3129206/179838566-4c7384e0-ae56-4b70-b617-e5dd8b904a08.png)

* Dates run 18,17,16,11,17,14,10,03
* Nothing before July 3 - I used to be able to scroll back and get old items.

**Comment by davorg** [comment]
[perlanet.log](https://github.com/davorg/planetperl/files/9144474/perlanet.log)

Here's the log from the most recent run. Looks like LWP::Protocol::https isn't being installed.

(That addresses the missing items - not the strange ordering)

**Comment by davorg** [comment]
[This commit](https://github.com/davorg/planetperl/commit/993c8746a00912df705f91f5872e2e8a0fe56a91) fixes the missing items. The strange order will require more investigation tomorrow.

**Comment by matthewpersico** [comment]
I haven't noticed any more strange ordering.
