### ISSUE TITLE
Link GitHub to the Website

### ISSUE THREAD

**Issue by rwp0** [davorg/planetperl#23]
Since it's the upstream source code repository that generates the website below automatically on commits:

https://perl.theplanetarium.org/

![image](https://user-images.githubusercontent.com/68062695/221940874-9f7353c6-a34d-4e86-b7b3-c5194df81be2.png)

We could add the website URL in the About section to be promptly visible to the users to get the idea quickly.

---

And perhaps also few more relevant GitHub tags (topics) for visibility such as [`perl`](https://github.com/topics/perl), `rss`, `feeds`, `news` etc.

**Comment by davorg** [comment]
Good idea. Done.
