### ISSUE TITLE
allow the user to filter the sources

### ISSUE THREAD

**Issue by szabgab** [davorg/planetperl#30]
Next to each source in the left pane there could be a checkbox that will allow the users to select which sources they would like to see. The selection could be stored in the browser in local storage and some javascript code could filter the posts based on this setting.

**Comment by davorg** [comment]
I like this idea. Let me see what I can knock up.

**Comment by davorg** [comment]
Looks like that's working now.

**Comment by szabgab** [comment]
Nice!
