### ISSUE TITLE
No need to commit the generated html pages back to git

### ISSUE THREAD

**Issue by szabgab** [davorg/planetperl#38]
* assuming it does not reuse the files there like a cache

I already did this with the [CPAN::Digger](https://github.com/szabgab/CPAN-Digger/)

See this commit: https://github.com/szabgab/CPAN-Digger/commit/06169dfef7476496529313d6399333a8e384630c

In order for this to work you also need to configure GitHub:  Settings/Pages   Set the "Source" to "GitHub Actions" (was Deploy from a branch). No need to "install" it, that would just create a yaml file, but you already have that.

**Comment by davorg** [comment]
Yeah. Like I wrote in my [blog post about this](https://dev.to/davorg/deploying-github-pages-site-with-github-workflows-3bhh):

> Now I'm deploying the sites from artifacts, there is no need for the generated site to actually exist in the repo. That might well make a few things quite a bit easier.

I've got several sites that use this pattern. I'm still considering whether removing the site from the repo is a net positive or negative :-)

**Comment by szabgab** [comment]
Sorry, I did not read the blog post in detail.

**Comment by davorg** [comment]
Done (a while ago!) in 59f5f455910d2b9b8da2718803e11677dd5f9391, d6244ab62d7ce619b3d4da1673e4b191ca5398c3 and 007d6fe5a20077c1716224136150f22b7ba2c030
