### ISSUE TITLE
Should we add reddit's r/perl as a feed?

### ISSUE THREAD

**Issue by matthewpersico** [davorg/planetperl#39]
I hit PlanetPerl and r/perl every day. Is r/perl able to be added to PlanetPerl?

**Comment by matthewpersico** [comment]
Looks like this is the url: https://www.reddit.com/r/perl.rss

**Comment by davorg** [comment]
We could, of course. But how often is there a post on /r/perl that isn't already covered by one of the existing feeds?

[FX: Time passes]

Ok, I've just looked and the answer is "about half". So, yes, I think it's worth adding. Do you want to send a PR?

**Comment by matthewpersico** [comment]
> Ok, I've just looked and the answer is "about half". So, yes, I think it's worth adding. Do you want to send a PR?

#40

**Comment by matthewpersico** [comment]
That was a quick merge! How often do you rebuild?

**Comment by matthewpersico** [comment]
> That was a quick merge! How often do you rebuild?

Apparently, on merge!

**Comment by davorg** [comment]
https://github.com/davorg/planetperl/blob/master/.github/workflows/buildsite.yml#L3
