### ISSUE TITLE
No updates since November 9 2023?

### ISSUE THREAD

**Issue by trwyant** [davorg/planetperl#45]
There appear to have been no updates since November 9 2023. At least, when I visit the last entry I see is [Enable gzip with LWP Perl [duplicate]](https://stackoverflow.com/questions/77453309/enable-gzip-with-lwp-perl) dated Thursday 09 November 2023 12:46

**Comment by davorg** [comment]
Thanks for pointing that out. It seems that GitHub Actions disables crontab-driven workflows if they aren't updated for 60 days - and that's what happened here. I've reactivated the workflow and will keep a closer eye on deactivations in the future.
