### ISSUE TITLE
No news since 2024/05/16

### ISSUE THREAD

**Issue by matthewpersico** [davorg/planetperl#52]
Is something wrong with the site? I know Perl usage is declining but there's no news since Sunday? At the very least, https://perlweekly.com/latest.html should be there and it is not.

**Comment by davorg** [comment]
So there's a rule with scheduled GitHub Actions (which is what drives the site) that if you don't commit something every 60 (or maybe 90) days, then they turn the action off. They usually email to warn when that's going to happen, but I don't think I've seen one recently.

Anyway, I've told them to re-enable the action - and a new version of the site has just been built. We should be ok for the next two or three months :-)

Thanks for the heads-up.

**Comment by matthewpersico** [comment]
It's two months and no news since 7/15...
